# Generated by Django 5.0.3 on 2024-04-18 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0011_auto_20200508_0913"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentextra",
            name="id",
        ),
        migrations.RemoveField(
            model_name="teacherextra",
            name="id",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="studentextra",
            name="cl",
            field=models.CharField(
                choices=[
                    ("one", "one"),
                    ("two", "two"),
                    ("three", "three"),
                    ("four", "four"),
                    ("five", "five"),
                    ("six", "six"),
                    ("form1", "form1"),
                    ("form2", "form2"),
                    ("form3", "form3"),
                    ("Gap year", "Gap year"),
                ],
                default="one",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="studentextra",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacherextra",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
